import datetime
import random

from castle_token.fingerprint import index0, index1, index2


def preset2(init_time):
    zero = [
        index0.index0('MacIntel', init_time),
        index0.index1('Google Inc.', init_time),
        index0.index2('en-US', init_time),
        index0.index3(8),
        index0.index4(1280, 1280, 800, 752),
        index0.index5(24),
        index0.index6(22),
        index0.index7(1.5),
        index0.index8(0, 0),
        index0.index9(['application/pdf', 'text/pdf']),
        index0.index10(['PDF ViewerPortable Document Format2internal-pdf-viewer', 'Chrome PDF ViewerPortable Document Format2internal-pdf-viewer', 'Chromium PDF ViewerPortable Document Format2internal-pdf-viewer', 'Microsoft Edge PDF ViewerPortable Document Format2internal-pdf-viewer', 'WebKit built-in PDFPortable Document Format2internal-pdf-viewer']),
        index0.index11([False, False, False, False, False, True, True, True, True, True, True, True]),
        index0.index12('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36', init_time),
        index0.index13('3e43e474', init_time),
        index0.index14([True, True, True]),
        index0.index17('20030107', init_time),
        index0.index18('1bcc6dab', init_time),
        index0.index19('ANGLE (Apple, ANGLE Metal Renderer: Apple M4 Pro, Unspecified Version)', init_time),
        index0.index20('1970/3/1 9:00:00', init_time),
        index0.index21([False]*8),
        index0.index22(33),
        index0.index24(random.randint(10000, 13000)),
        index0.index25('Maximum call stack size exceeded', init_time),
        index0.index26('RangeError', init_time),
        index0.index27(1034),
        index0.index28('00'),
        index0.index29("Cannot read properties of undefined (reading 'b')", init_time),
        index0.index30(['vendorSub~~~function get vendorSub() { [native code] }', 'productSub~~~function get productSub() { [native code] }', 'vendor~~~function get vendor() { [native code] }', 'maxTouchPoints~~~function get maxTouchPoints() { [native code] }', 'scheduling~~~function get scheduling() { [native code] }', 'userActivation~~~function get userActivation() { [native code] }', 'geolocation~~~function get geolocation() { [native code] }', 'doNotTrack~~~function get doNotTrack() { [native code] }', 'connection~~~function get connection() { [native code] }', 'plugins~~~function get plugins() { [native code] }', 'mimeTypes~~~function get mimeTypes() { [native code] }', 'pdfViewerEnabled~~~function get pdfViewerEnabled() { [native code] }', 'webkitTemporaryStorage~~~function get webkitTemporaryStorage() { [native code] }', 'webkitPersistentStorage~~~function get webkitPersistentStorage() { [native code] }', 'hardwareConcurrency~~~function get hardwareConcurrency() { [native code] }', 'cookieEnabled~~~function get cookieEnabled() { [native code] }', 'appCodeName~~~function get appCodeName() { [native code] }', 'appName~~~function get appName() { [native code] }', 'appVersion~~~function get appVersion() { [native code] }', 'platform~~~function get platform() { [native code] }', 'product~~~function get product() { [native code] }', 'userAgent~~~function get userAgent() { [native code] }', 'language~~~function get language() { [native code] }', 'languages~~~function get languages() { [native code] }', 'onLine~~~function get onLine() { [native code] }', 'webdriver~~~function get webdriver() { [native code] }', 'getGamepads~~~function getGamepads() { [native code] }', 'javaEnabled~~~function javaEnabled() { [native code] }', 'sendBeacon~~~function sendBeacon() { [native code] }', 'vibrate~~~function vibrate() { [native code] }', 'windowControlsOverlay~~~function get windowControlsOverlay() { [native code] }', 'constructor~~~function Navigator() { [native code] }', 'deprecatedRunAdAuctionEnforcesKAnonymity~~~functio…unAdAuctionEnforcesKAnonymity() { [native code] }', 'protectedAudience~~~function get protectedAudience() { [native code] }', 'bluetooth~~~function get bluetooth() { [native code] }', 'storageBuckets~~~function get storageBuckets() { [native code] }', 'clipboard~~~function get clipboard() { [native code] }', 'credentials~~~function get credentials() { [native code] }', 'keyboard~~~function get keyboard() { [native code] }', 'managed~~~function get managed() { [native code] }', 'mediaDevices~~~function get mediaDevices() { [native code] }', 'storage~~~function get storage() { [native code] }', 'serviceWorker~~~function get serviceWorker() { [native code] }', 'virtualKeyboard~~~function get virtualKeyboard() { [native code] }', 'wakeLock~~~function get wakeLock() { [native code] }', 'deviceMemory~~~function get deviceMemory() { [native code] }', 'userAgentData~~~function get userAgentData() { [native code] }', 'login~~~function get login() { [native code] }', 'ink~~~function get ink() { [native code] }', 'mediaCapabilities~~~function get mediaCapabilities() { [native code] }', 'devicePosture~~~function get devicePosture() { [native code] }', 'hid~~~function get hid() { [native code] }', 'locks~~~function get locks() { [native code] }', 'gpu~~~function get gpu() { [native code] }', 'mediaSession~~~function get mediaSession() { [native code] }', 'permissions~~~function get permissions() { [native code] }', 'presentation~~~function get presentation() { [native code] }', 'serial~~~function get serial() { [native code] }', 'usb~~~function get usb() { [native code] }', 'xr~~~function get xr() { [native code] }', 'adAuctionComponents~~~function adAuctionComponents() { [native code] }', 'runAdAuction~~~function runAdAuction() { [native code] }', 'canLoadAdAuctionFencedFrame~~~function canLoadAdAuctionFencedFrame() { [native code] }', 'canShare~~~function canShare() { [native code] }', 'share~~~function share() { [native code] }', 'clearAppBadge~~~function clearAppBadge() { [native code] }', 'getBattery~~~function getBattery() { [native code] }', 'getUserMedia~~~function getUserMedia() { [native code] }', 'requestMIDIAccess~~~function requestMIDIAccess() { [native code] }', 'requestMediaKeySystemAccess~~~function requestMediaKeySystemAccess() { [native code] }', 'setAppBadge~~~function setAppBadge() { [native code] }', 'webkitGetUserMedia~~~function webkitGetUserMedia() { [native code] }', 'clearOriginJoinedAdInterestGroups~~~function clearOriginJoinedAdInterestGroups() { [native code] }', 'createAuctionNonce~~~function createAuctionNonce() { [native code] }', 'joinAdInterestGroup~~~function joinAdInterestGroup() { [native code] }', 'leaveAdInterestGroup~~~function leaveAdInterestGroup() { [native code] }', 'updateAdInterestGroups~~~function updateAdInterestGroups() { [native code] }', 'deprecatedReplaceInURN~~~function deprecatedReplaceInURN() { [native code] }', 'deprecatedURNToURL~~~function deprecatedURNToURL() { [native code] }', 'getInstalledRelatedApps~~~function getInstalledRelatedApps() { [native code] }', 'getInterestGroupAdAuctionData~~~function getInterestGroupAdAuctionData() { [native code] }', 'registerProtocolHandler~~~function registerProtocolHandler() { [native code] }', 'unregisterProtocolHandler~~~function unregisterProtocolHandler() { [native code] }', 'constructor~~~function Navigator() { [native code] }', '__defineGetter__~~~', '__defineSetter__~~~', 'hasOwnProperty~~~', '__lookupGetter__~~~', '__lookupSetter__~~~', 'isPrototypeOf~~~', 'propertyIsEnumerable~~~', 'toString~~~', 'valueOf~~~', '__proto__~~~', 'toLocaleString~~~']),
        index0.index31([2, 2, 0, 2, 1, 2, 2, 2])
    ]
    one = [
        index1.index0(),
        index1.index1('Asia/Shanghai', init_time),
        index1.index2(['en-US', 'en', 'zh-CN'], init_time),
        index1.index6(6),
        index1.index10([True, False, True, False]),
        index1.index12(80),
        index1.index13([False]*11),
        index1.index14(False),
        index1.index16([False]*9),
        index1.index17([False, False, False, False, True, True, True, False, False, True, False, False, False, True, False]),
        index1.index18(False),
        index1.index21('01000000'),
        index1.index22('en-US', init_time),
        index1.index24(1280,1280,752,665),
        index1.index26(False),
        index1.index27([True, False, False, False]),
        index1.index28('arm', init_time),
        index1.index29('', init_time),
        index1.index30('142.0.7444.60', init_time)
    ]
    two = [
        index2.index0("macOS", init_time),
        index2.index1("26.0.1", init_time),
        index2.index2("Google Chrome"),
        index2.index3(0),
        index2.index4(datetime.datetime.fromtimestamp(init_time / 1000).minute),
        index2.index5("x.com", init_time),
        index2.index6("{}", init_time),
        index2.index7(
            [
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                True,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
            ]
        ),
        index2.index8(2),
        index2.index9(0),
        index2.index10(13),
        index2.index11(2790),
        index2.index12(
            [
                0,
                0,
                0,
                0,
                1.399999976158142,
                1.399999976158142,
                1.399999976158142,
                0,
                70.19999998807907,
            ]
        ),
        index2.index13(False),
        index2.index14([False, False, False, False]),
        index2.index15("Illegal invocation", init_time),
        index2.index16([3760000000, 91700000]),
        index2.index17([False, False, False, False, False, True, False, False]),
        index2.index18(1280,1280,665,752),
        index2.index19(0, 0),
        index2.index20("landscape-primary", init_time),
        index2.index21(0),
        index2.index22(15, 15),
        index2.index23(85),
        index2.index24('en', init_time),
        index2.index25(26),
        index2.index26(7),
        index2.index27(19),
        index2.index28('macOS', init_time),
        index2.index29(82),
        index2.index30('-1837256875', init_time),
    ]
    return [zero, one, two, [], []]
